{
  "build_from": {
    "aarch64": "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19",
    "amd64": "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19",
    "armv7": "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19"
  },
  "labels": {
    "io.hass.name": "Fotile Proxy",
    "io.hass.description": "A proxy server to intercept and modify traffic for Fotile devices, enabling local MQTT control.",
    "io.hass.version": "1.0.1",
    "io.hass.arch": "{arch}",
    "io.hass.type": "addon",
    "org.opencontainers.image.title": "Fotile Proxy",
    "org.opencontainers.image.description": "A proxy server to intercept and modify traffic for Fotile devices, enabling local MQTT control.",
    "org.opencontainers.image.version": "1.0.1",
    "org.opencontainers.image.authors": "seno",
    "org.opencontainers.image.licenses": "Apache-2.0",
    "org.opencontainers.image.source": "https://github.com/kaattz/FotileProxy",
    "org.opencontainers.image.documentation": "https://github.com/kaattz/FotileProxy"
  },
  "args": {}
}