slug: "fotile_proxy"
name: "Fotile Proxy"
version: "1.0.1" 
description: "A proxy server to intercept and modify traffic for Fotile devices, enabling local MQTT control."
arch:
  - "amd64"
  - "aarch64"
  - "armv7"

options:
  target_host: "api.fotile.com"
  mqtt_host: ""
  target_scheme: "https" 
  upstream_ip: "115.29.174.142" 
  log_level: "INFO"
schema:
  target_host: str
  mqtt_host: str
  target_scheme: str
  upstream_ip: str
  log_level: list(DEBUG|INFO|WARNING|ERROR)

ports:
  "80/tcp": 80
ports_description:
  "80/tcp": "HTTP Proxy Port for Fotile devices"

startup: application
boot: "auto"
init: false
host_network: false

hassio_api: true
hassio_role: default