slug: "fotile_proxy"
name: "Fotile Proxy"
version: "1.0.1" 
description: "A proxy server to intercept and modify traffic for Fotile devices, enabling local MQTT control."
arch:
  - "amd64"
  - "aarch64"
  - "armv7"

options:
  target_host: ""
schema:
  target_host: str

ports:
  "80/tcp": 80
ports_description:
  "80/tcp": "HTTP Proxy Port for Fotile devices"

startup: application
boot: "auto"
init: false
host_network: false

hassio_api: true
hassio_role: default